codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

  flags:
    backend:
      paths:
        - analysis/
        - coaching_mcp/
        - api/
        - gong/
        - db/
      target: 70%
      threshold: 2%

    frontend:
      paths:
        - frontend/
      target: 70%
      threshold: 2%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "**/__tests__/"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.test.py"
  - "frontend/.next/"
  - "frontend/node_modules/"
  - ".venv/"
  - "venv/"
  - "migrations/"
  - "scripts/"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

github_checks:
  annotations: true
